document.writeln("<footer class=\'footer row\'>");
document.writeln("    <dl class=\'col-xs-6 text-center\'>");
document.writeln("        <dd><a href=\'about.html\'>关于我们</a></dd>");
document.writeln("        <dt class=\'line\'></dt>");
document.writeln("        <dt><a href=\'about.html'>企业概述</a></dt>");
document.writeln("        <dt><a href=\'lianhua.html\'>联华实业</a></dt>");
document.writeln("        <dt><a href=\'about.html\'>企业愿景</a></dt>");
document.writeln("        <dt><a href=\'#\'>发展历程</a></dt>");
document.writeln("    </dl>");
document.writeln("    <dl class=\'col-xs-6 text-center\'>");
document.writeln("        <dd><a href=\'contact.html\'>加入我们</a></dd>");
document.writeln("        <dt class=\'line\'></dt>");
document.writeln("        <dt><a href=\'#\'>招聘岗位</a></dt>");
document.writeln("        <dt><a href=\'#\'>加盟洽谈</a></dt>");
document.writeln("        <dt><a href=\'#\'>经销商加盟洽谈</a></dt>");
document.writeln("    </dl>");
document.writeln("    <div class=\'col-xs-12 remark\'>");
document.writeln("        <div class=\'box\'>");
document.writeln("            <p>鲁ICP备09062917号-2 &nbsp;&nbsp;2017-2019 烟台台华食品实业有限公司</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");