document.writeln("<nav class=\'navbar navbar-default navbar-fixed-top\' id=\'nav\' role=\'navigation\'>");
document.writeln("    <div class=\'navbar-header\'>");
document.writeln("        <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'#navbar-menu\'>");
document.writeln("            <span class=\'sr-only\'>切换导航</span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("        </button>");
document.writeln("        <a href=\'#\' class=\'navbar-brand nav-title\'><img class=\'logo\' src=\'image/logo.png\' alt=\'\'></a>");
document.writeln("    </div>");
document.writeln("    <div class=\'collapse navbar-collapse\' id=\'navbar-menu\'>");
document.writeln("        <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("            <li id=\'index\'><a href=\'index.html\'>首页</a></li>");
document.writeln("            <li id=\'introduce\'><a href=\'introduce.html\'>产品介绍</a></li>");
document.writeln("            <li id=\'bake\'><a href=\'bake.html\'>烘焙教室</a></li>");
document.writeln("            <li id=\'sell\'><a href=\'sell.html\'>销售据点</a></li>");
document.writeln("            <li id=\'brand\'><a href=\'brand.html\'>品牌故事</a></li>");
document.writeln("            <li id=\'blog\'><a href=\'blog.html\'>部落客</a></li>");
document.writeln("            <li id=\'mall\'><a href=\'mall.html\'>台华商城</a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</nav>");